export const TYPES = {
  GET_ALL_NOTES: "GET_ALL_NOTES",
  ADD_NOTE_TO_FORM: "ADD_NOTE_TO_FORM",
  IS_EDITING_NOTE: "IS_EDITING_NOTE",
  SAVE_NOTE: "SAVE_NOTE",
  UPDATE_NOTE: "UPDATE_NOTE",
  DELETE_NOTE: "DELETE_NOTE",
};
